import type { BlogPost, Trade } from '../types';

export const mockPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Why Bitcoin Matters for Moms in 2025',
    excerpt: "Bitcoin isn't just for tech bros. Here's why every mom should understand crypto and how it can secure your family's financial future.",
    feature_image: 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=800&q=80',
    tag: 'Beginners Guide',
    reading_time: 5,
    author: 'Mel',
    published_at: '2025-02-10T10:00:00Z',
    slug: 'why-bitcoin-matters-for-moms',
  },
  {
    id: '2',
    title: 'My First $200 Trading Bitcoin',
    excerpt: 'I was terrified to make my first trade. Here\'s exactly what happened, what I learned, and how you can avoid my mistakes.',
    feature_image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80',
    tag: 'Trade Ideas',
    reading_time: 7,
    author: 'Mel',
    published_at: '2025-02-08T10:00:00Z',
    slug: 'my-first-200-trading-bitcoin',
  },
  {
    id: '3',
    title: '3 Stocks I\'m Watching This Week',
    excerpt: 'The market has been volatile but there are clear opportunities. Here are the three stocks on my watchlist and why.',
    feature_image: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&q=80',
    tag: 'Trade Ideas',
    reading_time: 4,
    author: 'Mel',
    published_at: '2025-02-05T10:00:00Z',
    slug: '3-stocks-watching-this-week',
  },
  {
    id: '4',
    title: 'How to Set Up Your First Trade',
    excerpt: 'A step-by-step walkthrough for complete beginners. From opening your account to placing your first trade safely.',
    feature_image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    tag: 'Beginners Guide',
    reading_time: 8,
    author: 'Mel',
    published_at: '2025-02-01T10:00:00Z',
    slug: 'how-to-set-up-first-trade',
  },
  {
    id: '5',
    title: 'Avoiding Common Beginner Mistakes',
    excerpt: "I made every mistake in the book so you don't have to. From over-trading to ignoring stop losses, here's what NOT to do.",
    feature_image: 'https://images.unsplash.com/photo-1559526324-593bc073d938?w=800&q=80',
    tag: 'Beginners Guide',
    reading_time: 6,
    author: 'Mel',
    published_at: '2025-01-28T10:00:00Z',
    slug: 'avoiding-common-beginner-mistakes',
  },
  {
    id: '6',
    title: 'Understanding Risk Management',
    excerpt: 'The #1 rule in trading is protecting your capital. Here\'s how I manage risk on every single trade I take.',
    feature_image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    tag: 'Beginners Guide',
    reading_time: 5,
    author: 'Mel',
    published_at: '2025-01-22T10:00:00Z',
    slug: 'understanding-risk-management',
  },
];

export const mockTrades: Trade[] = [
  {
    id: '1',
    userId: 'demo',
    token: 'BITCOIN',
    direction: 'long',
    entryPrice: 43250,
    stopLoss: 42500,
    takeProfit: 45500,
    riskReward: '1:3',
    positionSize: 0.1,
    valueTraded: 4325,
    timeframe: '4hr',
    leverage: 1,
    cause: 'Strong support at $42,500, bullish momentum, targeting previous high',
    closePrice: 44100,
    status: 'closed',
    profitLoss: 85,
    profitLossPercent: 1.96,
    winLoss: 'win',
    createdAt: { toDate: () => new Date('2025-02-15T09:00:00Z') } as any,
    updatedAt: { toDate: () => new Date('2025-02-15T15:00:00Z') } as any,
  },
  {
    id: '2',
    userId: 'demo',
    token: 'SOLANA',
    direction: 'short',
    entryPrice: 105.50,
    stopLoss: 108.00,
    takeProfit: 100.50,
    riskReward: '1:2',
    positionSize: 20,
    valueTraded: 2110,
    timeframe: '1hr',
    leverage: 1,
    cause: 'Bearish divergence on RSI, resistance at $108',
    status: 'open',
    createdAt: { toDate: () => new Date('2025-02-18T14:00:00Z') } as any,
    updatedAt: { toDate: () => new Date('2025-02-18T14:00:00Z') } as any,
  },
];
